"""Update localuser model

Revision ID: 00319d0392bd
Revises: 4bda913bd1b7
Create Date: 2023-06-27 10:25:15.801748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00319d0392bd'
down_revision = '4bda913bd1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.drop_constraint('local_users_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('username')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('local_users_username_key', ['username'])
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
