"""Remove local_id primary key

Revision ID: 09aa2ab8bb0f
Revises: 0d6cff20f888
Create Date: 2023-06-27 14:41:12.074781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09aa2ab8bb0f"
down_revision = "0d6cff20f888"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "local_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "local_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    # ### end Alembic commands ###
