"""Add local_id primary key

Revision ID: 0d6cff20f888
Revises: e74ab29140c2
Create Date: 2023-06-27 14:38:34.661375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d6cff20f888"
down_revision = "e74ab29140c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("local_id", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("local_id")

    # ### end Alembic commands ###
