"""Update product to include image and count

Revision ID: 24836749cc03
Revises: 25463e8ff4f8
Create Date: 2023-06-26 13:04:19.898390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24836749cc03"
down_revision = "25463e8ff4f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("count")
        batch_op.drop_column("image")

    # ### end Alembic commands ###
