"""Drop Wishlist and wishlist_product tables

Revision ID: 25463e8ff4f8
Revises: 89dc6e4c6409
Create Date: 2023-06-23 09:40:08.932388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25463e8ff4f8'
down_revision = '89dc6e4c6409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_products')
    op.drop_table('wishlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wishlists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wishlists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('wishlist_products',
    sa.Column('wishlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_wishlist_products_product_id_products'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name='fk_wishlist_products_wishlist_id_wishlists'),
    sa.PrimaryKeyConstraint('wishlist_id', 'product_id', name='wishlist_products_pkey')
    )
    # ### end Alembic commands ###
