"""Drop in stock from product table

Revision ID: 29691203ba4d
Revises: 088ffc61c60e
Create Date: 2023-07-03 09:11:44.721550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29691203ba4d'
down_revision = '088ffc61c60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
