"""Rename LocalUser to User model

Revision ID: 2a9a8bc7daae
Revises: e85b3e9036b9
Create Date: 2023-06-27 10:38:51.836265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a9a8bc7daae"
down_revision = "e85b3e9036b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("profile_pic", sa.String(), nullable=True),
        sa.Column("_password_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.drop_table("local_users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "local_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("_password_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("google_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("profile_pic", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="local_users_pkey"),
        sa.UniqueConstraint("email", name="local_users_email_key"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
