"""Add google_id as string

Revision ID: 52978cccfc80
Revises: dbdfdad42e40
Create Date: 2023-06-27 11:22:41.363447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52978cccfc80"
down_revision = "dbdfdad42e40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###
