"""Change User id to String type

Revision ID: 6da5b122651c
Revises: cc3ebc33a507
Create Date: 2023-06-15 18:03:35.355449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6da5b122651c"
down_revision = "cc3ebc33a507"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=False
        )

    # ### end Alembic commands ###
