"""Drop google_id

Revision ID: 857d8c711915
Revises: 8eb84e8a0732
Create Date: 2023-06-27 11:18:43.647838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "857d8c711915"
down_revision = "8eb84e8a0732"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("users_google_id_key", type_="unique")
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.create_unique_constraint("users_google_id_key", ["google_id"])

    # ### end Alembic commands ###
