"""Add LocalUser model

Revision ID: 89dc6e4c6409
Revises: 6da5b122651c
Create Date: 2023-06-22 11:21:16.128680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89dc6e4c6409"
down_revision = "6da5b122651c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "local_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("_password_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("local_users")
    # ### end Alembic commands ###
