"""Remove primary key from id, add to local_id

Revision ID: b401c7144f03
Revises: 09aa2ab8bb0f
Create Date: 2023-06-27 14:46:04.158993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b401c7144f03"
down_revision = "09aa2ab8bb0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
        )
        batch_op.alter_column(
            "local_id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "local_id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
        )

    # ### end Alembic commands ###
