"""Update User constraints

Revision ID: c5a9880d2247
Revises: 2a9a8bc7daae
Create Date: 2023-06-27 10:49:22.634152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c5a9880d2247"
down_revision = "2a9a8bc7daae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("users_email_key", type_="unique")
        batch_op.create_unique_constraint(None, ["google_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint("users_email_key", ["email"])

    # ### end Alembic commands ###
