"""Drop google_id

Revision ID: d33eabeb43e8
Revises: 52978cccfc80
Create Date: 2023-06-27 11:24:54.206217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d33eabeb43e8"
down_revision = "52978cccfc80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
