"""Drop google_id

Revision ID: dbdfdad42e40
Revises: c95edded3f4f
Create Date: 2023-06-27 11:21:41.530670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdfdad42e40'
down_revision = 'c95edded3f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
