"""Update count to quantity

Revision ID: dcad6a9800d6
Revises: 24836749cc03
Create Date: 2023-06-26 13:29:42.512614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcad6a9800d6'
down_revision = '24836749cc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
