"""drop google_id, change to id

Revision ID: e74ab29140c2
Revises: e92fdbca6add
Create Date: 2023-06-27 14:32:58.011693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74ab29140c2'
down_revision = 'e92fdbca6add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('users_google_id_key', type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_google_id_key', ['google_id'])
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
