"""Drop user model

Revision ID: e85b3e9036b9
Revises: 00319d0392bd
Create Date: 2023-06-27 10:36:31.739387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e85b3e9036b9"
down_revision = "00319d0392bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("profile_pic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.VARCHAR(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.UniqueConstraint("email", name="users_email_key"),
    )
    # ### end Alembic commands ###
