"""Add unique constraint to google_id

Revision ID: e92fdbca6add
Revises: d3886194cbd8
Create Date: 2023-06-27 13:57:34.084852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e92fdbca6add"
down_revision = "d3886194cbd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["google_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
